greenbone/autohooks

autohooks/precommit/run.py, autohooks/utils.py
Allow to put autohooks plugins in a local .autohooks directory of the current git repo. This will provide repo specific hooks not being available as a package on pypi.
=> Load plugins from local repo

CHANGELOG.md, autohooks/api/git.py, autohooks/utils.py
autohooks plugins stash unrelated changes before applying formatting. When un-stashing the unrelated changes these changes my conflict with the changes made by the formatter plugins. This change shows a message in this case and removes the created *.rej* files
**Checklist**:
- [N/A] Tests
=> Unstash error handling

CHANGELOG.md, README.md, autohooks/config.py, tests/test_config.py
Instead of config.get('foo').get('bar') allow config.get('foo', 'bar')
too.
**Checklist**:
=> Allow for a simplified access to a config

CHANGELOG.md, autohooks/precommit/run.py
Fail git hook if a plugin can't be executed.
References #25 
**Checklist**:
- [n/a] Tests
- [n/a] Documentation
=> Mandatory hooks

README.md
When installing the autohooks python package the desired mode should
already be configured. Therefore split the installation into four steps.
**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/autohooks/blob/master/CHANGELOG.md) Entry
=> Update installation procedure doc

CHANGELOG.md, autohooks/api/__init__.py, autohooks/cli/__init__.py, autohooks/cli/activate.py, autohooks/cli/check.py, autohooks/precommit/run.py, autohooks/terminal.py, tests/api/test_path.py, tests/api/test_terminal.py, tests/test_terminal.py
Improve console output formatting. 
* Add Terminal class for console output
* Allow for indentation of following output
* Display message status at the right end of the current console line
E.g. hook output is now:
```
autohooks => pre-commit
Running autohooks.plugins.black                                 
Running black pre-commit hook
No staged files for black available                                        [ ok ]                                                                                                                                                                                                  
Running autohooks.plugins.pylint                                 
Running pylint pre-commit hook
No files to lint                                                           [ ok ] …
```
=> Terminal output

CHANGELOG.md, autohooks/cli/check.py
If the .git/hooks/pre-commit file doesn't exist running autohooks check
should not fail and instead display that the file is missing and
autohooks activate should be run.
**Checklist**:
=> Allow to run autohooks check if no pre-commit file exists

CHANGELOG.md, MANIFEST.in, README.md, RELEASE.md
=> Dont rely on auto activation

CHANGELOG.md, autohooks/terminal.py, poetry.lock, pyproject.toml, tests/test_terminal.py
* Ensure less issues with calculating a terminal width
* Add a single place to query the terminal width
* Improve readability and reliability of the terminal tests
**Checklist**:
- [n/a] Documentation
=> Improve Terminal

CHANGELOG.md, README.md
Due to the long inactivity of the pipenv project the tools has fallen
behind poetry and really has some strange quirks. poetry is a bit
cleaner and seems to win the race. By using poetry also the issues with
dependabot are fixed.
**Checklist**:
- [n/a] Tests
=> Recommend poetry mode instead of pipenv

autohooks/precommit/run.py, autohooks/terminal.py, tests/test_terminal.py
If a line is larger than the terminals width, it will be broken correctly ... hopefully.
Changed the status from right to left, from text to symbol ...
Example:
```
ℹ autohooks => pre-commit
ℹ     Running autohooks.plugins.black
✓         Running black on autohooks/precommit/run.py
✓         Running black on autohooks/terminal.py
✓         Running black on tests/test_terminal.py
ℹ     Running autohooks.plugins.pylint
************* Module terminal
autohooks/terminal.py:70:12: E0602: Undefined variable 'part_line' (undefined-variable)
************* Module tests.test_terminal
tests/test_terminal.py:160:0: C0301: Line too long (184/80) (line-too-long)
tests/test_terminal.py:161:0: C0301: Line too long (176/80) (line-too-long)
✖         Linting error(s) found in autohooks/precommit/run.py, …
```
=> Line-breaks and other improvements for the terminal output

autohooks/cli/__init__.py, autohooks/cli/check.py, autohooks/terminal.py, poetry.lock, pyproject.toml
**What**:
Use the latest release for black auto formatter.
**Why**:
black has hopefully released the late beta version. this version contains changes that should make the formatting more stable.
**How**:
Updated all code with `poetry run black autohooks tests`
**Checklist**:
=> Update black to 20.8b1

tests/test_hooks.py, tests/test_utils.py
Unit tests not passing on macOS.  autohooks leverage path resolving
whereas the test cases do not.
=> Unit tests not passing on macOS due to inconsistent path resolving

.circleci/config.yml, CHANGELOG.md, README.md, pyproject.toml
**What**:
Drop Python 3.5 and 3.6 support, add Python 3.9
**Why**:
Python 3.5 is deprecated.
**How**:
**Checklist**:
=> Drop Python 3.5 and 3.6 support, add Python 3.9

CHANGELOG.md, autohooks/config.py, poetry.lock
**What**:
Fix a nasty issue with testing getting a config value with up to date tomlkit 0.7.2
**Why**:
The config_dict is some tomlkit extended dict class. With some tomlkit
0.7.1 or 0.7.2 a single test broke. At some place some of this dict
classes might return a proxy to a class and in the next iteration this
proxy doesn't work anymore because something is freed internally.
Therefore always copy the object to not free the data.
**How**:
**Checklist**:
=> Fix config test for tomlkit 0.7.2

.github/workflows/release-pontos.yml, CHANGELOG.md, autohooks/utils.py, tests/test_hooks.py, tests/test_utils.py
**What**:
* Using `getcwd` instead of `os.environ['PWD']`
**Why**:
* to fix Windows (?)
**How**:
**Checklist**:
=> Autohooks now uses getcwd instead of os.environ['PWD']

poetry.lock, pyproject.toml
**What**:
Remove direct dependency on packaging
**Why**:
The packaging library is not used in autohooks directly.
Fixes #322
**How**:
**Checklist**:
=> Change: Remove direct dependency on packaging

autohooks/cli/activate.py, autohooks/cli/check.py, autohooks/config.py, autohooks/settings.py, tests/__init__.py, tests/cli/test_activate.py, tests/test_config.py, tests/test_settings.py
**What**:
Improve installation, setup and usage of `autohooks activate` by writing the settings to the `pyproject.toml` file.
With this change the user doesn't need to change the `pyproject.toml` file manually during the setup.
**Why**:
Make the setup easier.
**How**:
**Checklist**:
=> Activate improvements

autohooks/cli/activate.py, tests/cli/test_activate.py
**What**:
Raise a warning if activate is run with installed hook
Requires https://github.com/greenbone/autohooks/pull/345 to be merged.
**Why**:
Most likely the user wanted to change something. Therefore a warning
should be raised because nothing is changed.
**How**:
**Checklist**:
=> Change: Raise a warning if activate is run with installed hook

autohooks/cli/__init__.py, autohooks/cli/check.py, autohooks/cli/plugins.py, autohooks/precommit/run.py, autohooks/settings.py, tests/__init__.py, tests/cli/test_check.py, tests/cli/test_plugins.py, tests/precommit/__init__.py, tests/precommit/test_run.py, tests/test_settings.py
**What**:
Add a new CLI for adding, removing and listing autohooks plugins
**Why**:
Make plugin handling easier. Currently the plugins need to be changed by editing the pyproject.toml file manually. This requires users to know TOML.
**How**:
**Checklist**:
=> Plugin CLI

autohooks/utils.py
**What**:
Fix an issue where is_split_env method is not runnable on windows
**Why**:
Shell script running in subprocess is not runnable on windows.
**How**:
Catch FileNotFoundError during split env checking.
**Checklist**:
=> Fix : Fix an issue where is_split_env method is not runable on windows

autohooks/template.py, tests/test_template.py
**What**:
Fix: Change pre-commit shebang line when using poetry
**Why**:
pre-commit not able to run on windows due to poetry doesn't create python3 alias in virtualenv.
**How**:
Change shebang from ``poetry run python3`` to ``poetry run python`` when using poetry mode.
**Checklist**:
=> Fix: Change pre-commit shebang line when using poetry

.github/workflows/ci-python.yml, autohooks/terminal.py, tests/api/test_terminal.py
**What**:
Change out terminal function to not apply formatting and escaping
This fixes the output of errors created by pylint which include ANSI color escapes. With this fix these output is displayed correctly again.
**Why**:
Fix pylint output.
**How**:
**Checklist**:
=> Fix: Change out terminal function to not apply formatting and escaping

poetry.lock, pyproject.toml
**What**:
Support rich >= 13.0 too
rich 13 didn't change the API just dropped support for older Python versions.
**Why**:
Allow to install current versions of rich.
**How**:
**Checklist**:
=> Change: Support rich >= 13.0 too

.github/workflows/ci-python.yml
Run GitHub action to check versioning for consistency
The version check got removed from the lint-python action and is now a standalone action.
DEVOPS-579
=> Change: Add GitHub action to check versioning for consistency

.github/workflows/ci-python.yml, .github/workflows/github-pages.yml
Fix workflows and enable poetry caching
Installing the furo sphinx theme with poetry 1.4.1 is broken currently. Therefore stick with poetry 1.4.0 for now. Enable caching of python packages to faster CI.
=> Fix workflows and enable poetry caching

README.md
Advertise the usage of the pyproject.toml file in README
autohooks uses the pyproject.toml file for its configuration. This is a key feature and should be advertised.
#511
=> Change: Advertise the usage of the pyproject.toml file in README

.github/workflows/ci-python.yml, .github/workflows/github-pages.yml
Use python-version input instead of version. Also drop pinning on poetry version 1.4.0. The underlying issue has been resolved already.
Resolve deprecation warnings in GitHub workflows
=> Change: Resolve deprecation warnings in GitHub workflows

.github/dependabot.yml, .github/workflows/conventional-commits.yml
Create conventional commits for dependabot
Change dependabot config to create convention commit messages. This allows to include dependency updates in the release changelogs.
Also require read permissions for repo contents.
=> Change: Create conventional commits for dependabot

.github/workflows/ci-python.yml, poetry.lock, pyproject.toml
Drop support for Python 3.8 and add Python 3.12
Only support current Python versions.
DEVOPS-776
=> Change: Drop support for Python 3.8 and add Python 3.12

.github/workflows/ci-python.yml
Fix: Linting in CI via ruff check
`ruff` is deprecated. ...
=> Fix: Linting in CI via ruff check

autohooks/config.py, tests/test_config.py
Improved Config classes
Allow to load a config from a string and to check if a key is set in a config.
=> Improved config
