- autohooks/api/path.py
- tests/api/test_path.py
Allow to match files against a list of patterns.
> Add a plugin api for matching files

- CHANGELOG.md
- autohooks/cli/activate.py
- autohooks/cli/check.py
- autohooks/config.py
- autohooks/precommit/run.py
Improve the check cli to validate all possible plugin configuration errors.
**Checklist**:
- [N/A] Tests
> Improve check cli

- CHANGELOG.md
- Pipfile
- Pipfile.lock
- autohooks/api/__init__.py
- autohooks/cli/check.py
- autohooks/precommit/run.py
- autohooks/terminal.py
- setup.py
Allow to create better terminal output messages in future
**Checklist**:
> Terminal output

- README.md
> Add section about howto write a autohooks plugin

- CHANGELOG.md
- RELEASE.md
- autohooks/version.py
Update changelog, version and release instructions after the release
> After release

- .circleci/config.yml
- autohooks/api/git.py
- autohooks/precommit/run.py
> Improve circleci settings and run linting

- autohooks/utils.py
- tests/test_utils.py
**Checklist**:
- [n/a] [CHANGELOG](https://github.com/greenbone/autohooks/blob/master/CHANGELOG.md) Entry
- [n/a] Documentation
> Additional tests

- README.md
Add a link to the new `autohooks-plugin-isort` plugin.
**Checklist**:
> Add link to 'autohooks-plugin-isort'

- .pylintrc
- Pipfile
- Pipfile.lock
- autohooks/version.py
- pyproject.toml
> Updates (dependencies, configs, ...)

- CHANGELOG.md
- README.md
- autohooks/cli/__init__.py
- autohooks/setting.py
- autohooks/template.py
- tests/test_setting.py
- tests/test_template.py
> Poetry mode

- Pipfile
- Pipfile.lock
- autohooks/config.py
- pyproject.toml
Also update other deps in the lock file as Pipfile doesn't allow to
update only black and it's sub-dependencies.
**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/autohooks/blob/master/CHANGELOG.md) Entry
- [n/a] Documentation
> Update black to 19.10b0

- README.md
Reworked the README file. Corrected some spelling and wording.
**Checklist**:
> Rework of README

- .pylintrc
- CHANGELOG.md
- Pipfile
- Pipfile.lock
- autohooks/terminal.py
- setup.py
- tests/test_terminal.py
Reworked the whole `terminal.py` `Terminal` class by exchanging `blessings` with [`colorful`](https://github.com/timofurrer/colorful).
This should fix #43 and #44 ...
**Checklist**:
> Make colors great again

- .circleci/config.yml
- tests/test_terminal.py
Format with black and ensure tests get linted on ci
> Cleanup tests

- README.md
Ensure users will be aware of the coreutils issue in #42.
> Add a section about the requirements to the readme

- .circleci/config.yml
- RELEASE.md
**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/autohooks/blob/master/CHANGELOG.md) Entry
> Auto deploy

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- autohooks/api/__init__.py
- autohooks/api/git.py
- autohooks/utils.py
- poetry.lock
Some minor changes I have missed to push in the last commit.
Also updated the PR Template ...
**Checklist**:
> Update pr template

- poetry.lock
- pyproject.toml
**What**:
pontos 0.3.0 will provide the release automation scripts.
**Why**:
pontos 0.3.0 will provide the release automation scripts and installed commands `pontos-version` and `pontos-release`.
**How**:
`poetry run pontos-version show`
**Checklist**:
> Update pontos to 0.3.0

- RELEASE.md
**What**:
Update release docs for using pontos
**Why**:
pontos got support for creating release automatically
**How**:
Last release was made with pontos.
**Checklist**:
> Update release docs for using pontos

- RELEASE.md
**What**:
Just a small addition, as this is necessary for the release ...
**Why**:
Incompleteness of Doc.
**How**:
**Checklist**:
> Added GITHUB_NAME to Release documentation

- .github/dependabot.yml
**What**:
Changing dependabot schedule to weekly
**Why**:
It's kind of messy to deal with dependabot daily ...
**How**:
**Checklist**:
> Changing dependabot schedule to weekly

- .github/workflows/ci-python.yml
**What**:
Start to use GitHub Actions for autohooks
**Why**:
**How**:
**Checklist**:
> Switch to GitHub Actions

- .github/workflows/codeql-analysis-python.yml
**What**:
Add a github actions workflow to scan for code vulnerabilities via codeql.
**Why**:
**How**:
**Checklist**:
> Scan for code vulnerabilities

- .github/workflows/release-pontos.yml
- poetry.lock
- pyproject.toml
**What**:
**Why**:
**How**:
**Checklist**:
> Release workflow with pontos.

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci-python.yml
- .github/workflows/codeql-analysis-python.yml
- CHANGELOG.md
- README.md
- RELEASE.md
**What**:
**Why**:
**How**:
**Checklist**:
> Use main, not master

- .github/CODEOWNERS
**What**:
**Why**:
**How**:
**Checklist**:
> Make devops responsible for this repository

- autohooks/api/git.py
**What**:
**Why**:
**How**:
**Checklist**:
> [Refactor] Remove `python35` workaround and add Documentation

- .github/workflows/ci-python.yml
- autohooks/api/git.py
- autohooks/utils.py
- tests/api/git/__init__.py
- tests/api/git/test_diff.py
- tests/api/git/test_status.py
**What**:
Start adding tests for the plugin git API
**Why**:
**How**:
**Checklist**:
> Improve test coverage

- autohooks/api/__init__.py
- autohooks/precommit/run.py
- autohooks/terminal.py
- poetry.lock
- pyproject.toml
- tests/api/test_terminal.py
- tests/test_terminal.py
**What**:
Fix the terminal API of autohooks. Plugins should only use the `autohooks.api` functions and we should not export functions from pontos here.
**Why**:
The terminal API of pontos is very likely to change a lot. Therefore don't depend on the current API.
**How**:
**Checklist**:
> Update terminal api

- pyproject.toml
**What**:
Change: Use up-to-date build system for poetry in pyproject.toml
**Why**:
poetrys interface for the build system has changed a while ago.
**How**:
**Checklist**:
> Change: Use up-to-date build system for poetry in pyproject.toml

- README.md
- autohooks/precommit/run.py
- autohooks/terminal.py
- poetry.lock
- pyproject.toml
- tests/test_terminal.py
**What**:
Allow to display a nice progress bar in the console
**Why**:
Improved UI
**How**:
**Checklist**:
> Rich progress

- README.md
**What**:
Add: Add an example for reporting progress to README
**Why**:
Usage example for reporting progress
**How**:
**Checklist**:
> Add: Add an example for reporting progress to README

- poetry.lock
**What**:
Update to latest versions of autohooks plugin black and pylint
**Why**:
Both plugins used a wrong API for reporting the progress.
**How**:
**Checklist**:
> Update to latest versions of autohooks plugin black and pylint

- .github/workflows/github-pages.yml
**What**:
Upload the correct content for GitHub pages
**Why**:
Fix path to the built html docs.
**How**:
**Checklist**:
> Upload the correct content for GitHub pages

- pyproject.toml
**What**:
**Why**:
**How**:
**Checklist**:
> Remove release.MD from pyproject.toml

- .github/workflows/ci-python.yml
- .github/workflows/codeql-analysis-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/github-pages.yml
- .github/workflows/release-pontos-manually.yml
- .github/workflows/release-pontos.yml
- pyproject.toml
**What**:
* Run autoformatter on all workflow files
* Add support for Python 3.11
* Run Python based actions on Python 3.10 by default now
* Update our actions to v2 versions
**Why**:
Get rid of workflow run warnings, support latest Python version
**How**:
**Checklist**:
> Change: Format workflows, update actions and support Python 3.11

- poetry.lock
**What**:
**Why**:
**How**:
**Checklist**:
> Refactor: Update Dependencies

- .github/workflows/ci-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/github-pages.yml
- .github/workflows/release-pontos.yml
- pyproject.toml
Use generic reusable workflows
Use our new generic reusable workflows where possible.
> Change: Use generic reusable workflows

- README.md
Mention new ruff plugin in README.md
Update README to mention the new ruff plugin. User should be made aware of that plugin.
> Change: Mention new ruff plugin in README.md

- .github/dependabot.yml
Grouping dependabot PRs
Less developer time
DEVOPS-804
> Change: Dependabot grouping

- .github/workflows/auto-merge.yml
Auto-merge workflow to activate auto-merge sqash in PRs
Save dev time
DEVOPS-804
> Add: Auto-merge workflow to activate auto-merge squash in PRs

- README.md
> Add missing reference to ruff

- README.md
- autohooks/cli/__init__.py
- poetry.lock
- pyproject.toml
Provide command completion for zsh and bash
Allow to install command completions for zsh and bash.
> Add: Provide command completion for zsh and bash

- autohooks/utils.py
added docstrings to utils.py module
> docs: documented utils.py
